window.combinedStations = {
    'Zürich HB': ['Zürich HB', 'Zürich, Sihlquai/HB', 'Zürich, Bahnhofstrasse/HB', 'Zürich, Bahnhofplatz/HB', 'Zürich, Bahnhofquai/HB'],
    'Zürich, Sihlquai/HB': ['Zürich HB', 'Zürich, Sihlquai/HB'],
    'Zürich, Bahnhofquai/HB': ['Zürich HB', 'Zürich, Bahnhofquai/HB'],
    'Zürich, Bahnhofstrasse/HB': ['Zürich HB', 'Zürich, Bahnhofstrasse/HB'],
    'Zürich, Bahnhofplatz/HB': ['Zürich HB', 'Zürich, Bahnhofplatz/HB'],
    'Zürich, Sihlpost/HB': ['Zürich HB', 'Zürich, Sihlpost/HB'],
    'Zürich Hardbrücke': ['Zürich Hardbrücke', 'Zürich Hardbrücke, Bahnhof'],
    'Zürich Hardbrücke, Bahnhof': ['Zürich Hardbrücke', 'Zürich Hardbrücke, Bahnhof'],
    'Basel SBB': ['Basel SBB', 'Basel, Bahnhof SBB', 'Basel, Bahnhofeingang Gundeldingen'],
    'Langenthal': ['Langenthal', 'Langenthal, Bahnhof'],
	'Herzogenbuchsee': ['Herzogenbuchsee', 'Herzogenbuchsee, Bahnhof'],
	'Aeschi SO, Bolkenstrasse': ['Aeschi SO, Bolkenstrasse', 'Aeschi SO, Kirche'],
	'Aeschi SO, Kirche': ['Aeschi SO, Bolkenstrasse', 'Aeschi SO, Kirche'],
    'Locarno': ['Locarno', 'Locarno FART', 'Locarno, Stazione'],
    'Burgdorf': ['Burgdorf', 'Burgdorf, Bahnhof'],
    'Moutier': ['Moutier', 'Moutier, gare'],
    'Meiringen': ['Meiringen', 'Meiringen, Bahnhof'],
	'Innertkirchen Grimseltor': ['Innertkirchen Grimseltor', 'Innertkirchen, Grimseltor'],
    'Brienz': ['Brienz', 'Brienz, Bahnhof'],
    'Gelterkinden': ['Gelterkinden', 'Gelterkinden, Bahnhof'],
    'Liestal': ['Liestal, Bahnhof', 'Liestal'],
    'Muttenz': ['Muttenz', 'Muttenz, Bahnhof'],
    'Sursee': ['Sursee', 'Sursee, Bahnhof'],
    'Airolo': ['Airolo', 'Airolo, Stazione'],
    'Ilanz': ['Ilanz', 'Ilanz, Bahnhof/Post'],
    'Horgen': ['Horgen', 'Horgen (See)'],
    'Meilen': ['Meilen', 'Meilen Autoquai'],
    'Zürich, Bürkliplatz': ['Zürich Bürkliplatz (See)', 'Zürich, Bürkliplatz'],
    'St. Stephan': ['St. Stephan', 'St. Stephan, Bahnhof'],
    'Sumiswald-Grünen': ['Sumiswald-Grünen', 'Sumiswald-Grünen, Bahnhof'],
    'Sumiswald-Grünen, Bahnhof': ['Sumiswald-Grünen', 'Sumiswald-Grünen, Bahnhof'],
    'Hasle-Rüegsau': ['Hasle-Rüegsau', 'Hasle-Rüegsau, Bahnhof'],
    'Hasle-Rüegsau, Bahnhof': ['Hasle-Rüegsau', 'Hasle-Rüegsau, Bahnhof'],
    'Oberburg': ['Oberburg, Geissrütti', 'Oberburg'],
    'Oberburg, Geissrütti': ['Oberburg, Geissrüti', 'Oberburg'],
	'Langnau i.E.': ['Langnau i.E.', 'Langnau i.E., Bahnhof'],
	'Langnau i.E., Bahnhof': ['Langnau i.E.', 'Langnau i.E., Bahnhof'],
	'Ramsei': ['Ramsei', 'Ramsei, Bahnhof'],
	'Ramsei, Bahnhof': ['Ramsei', 'Ramsei, Bahnhof'],
    'Luzern': ['Luzern', 'Luzern Bahnhofquai', 'Luzern, Bahnhof', 'Luzern, Inseliquai'],
    'Luzern Bahnhofquai': ['Luzern', 'Luzern Bahnhofquai'],
    'Münchenstein': ['Münchenstein, Bahnhof', 'Münchenstein'],
    'Laufen': ['Laufen, Bahnhof', 'Laufen'],
    'Aesch BL': ['Aesch BL, Bahnhof', 'Aesch BL'],
    'Dornach-Arlesheim': ['Dornach, Bahnhof', 'Dornach-Arlesheim'],
    'Dornach, Bahnhof': ['Dornach, Bahnhof', 'Dornach-Arlesheim'],
    'Basel Dreispitz': ['Basel Dreispitz, Bahnhof', 'Basel, Dreispitz', 'Basel Dreispitz'],
    'Luzern Verkehrshaus': ['Verkehrshaus-Lido', 'Luzern Verkehrshaus', 'Luzern, Verkehrshaus/Lido'],
    'Verkehrshaus-Lido': ['Verkehrshaus-Lido', 'Luzern, Verkehrshaus/Lido', 'Luzern Verkehrshaus'],
	'Kriens Mattenhof': ['Kriens, Sternmatt', 'Kriens Mattenhof', 'Kriens, Mattenhof'],
    'Langenthal, Bleichestrasse': ['Langenthal, Bleichestrasse', 'Langenthal, Mittelstrasse'],
    'Langenthal, Mittelstrasse': ['Langenthal, Bleichestrasse', 'Langenthal, Mittelstrasse'],
    'Langenthal Süd': ['Langenthal Süd', 'Langenthal Süd, Bahnhof'],
    'Huttwil, Bahnhof': ['Huttwil', 'Huttwil, Bahnhof'],
    'Zell LU': ['Zell LU', 'Zell LU, Bahnhof'],
    'Huttwil': ['Huttwil', 'Huttwil, Bahnhof'],
    'Schüpfheim': ['Schüpfheim', 'Schüpfheim, Bahnhof'],
    'Horw': ['Horw', 'Horw, Bahnhof'],
    'Brünig-Hasliberg': ['Brünig-Hasliberg', 'Brünig-Hasliberg, Bahnhof'],
    'Hasliberg Reuti, Gondelbahn': ['Hasliberg Reuti, Gondelbahn', 'Hasliberg Reuti (Gondelbahn)'],
    'Hasliberg Reuti (Gondelbahn)': ['Hasliberg Reuti, Gondelbahn', 'Hasliberg Reuti (Gondelbahn)'],
    'Meiringen (Luftseilbahn)': ['Meiringen (Luftseilbahn', 'Meiringen, Luftseilbahn'],
    'Meiringen, Luftseilbahn': ['Meiringen (Luftseilbahn)', 'Meiringen, Luftseilbahn'],
    'Wabern (Gurtenbahn)': ['Wabern b. Bern', 'Wabern (Gurtenbahn)', 'Wabern, Gurtenbahn'],
	'Ins [Gleis 11]': ['Ins', 'Ins, Bahnhof'],
	'Lüscherz, Bahnhof': ['Lüscherz', 'Lüscherz, Bahnhof'],
	'Lüscherz': ['Lüscherz', 'Lüscherz, Bahnhof'],
	'Bern Europaplatz, Bahnhof': ['Bern Europaplatz', 'Bern Europaplatz, Bahnhof'],
	'Bern Europaplatz': ['Bern Europaplatz', 'Bern Europaplatz, Bahnhof'],
	'Bern Brünnen Westside': ['Bern Brünnen Westside', 'Bern Brünnen Westside, Bahnhof'],
	'Bern Brünnen Westside, Bahnhof': ['Bern Brünnen Westside', 'Bern Brünnen Westside, Bahnhof'],
	'Oberdorf SO': ['Oberdorf SO', 'Oberdorf SO, Endhalt'],
	'Oberdorf SO, Endhalt': ['Oberdorf SO', 'Oberdorf SO, Endhalt'],
	'Schlieren, Heimeliweg': ['Urdorf', 'Schlieren, Heimeliweg'],
	'Urdorf': ['Urdorf', 'Schlieren, Heimeliweg'],
	'Unterengstringen, Sennenbüel': ['Unterengstringen, Sennenbüel', 'Unterengstringen, Sennenbüel N'],
	'Unterengstringen, Sennenbüel N': ['Unterengstringen, Sennenbüel', 'Unterengstringen, Sennenbüel N'],
	'Zürich, Pass. Sihlquai': ['Zürich HB', 'Zürich, Sihlquai/HB'],
	'Langenthal Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal, Industrie Nord': ['Langenthal Industrie Nord', 'Langenthal, Industrie Nord'],
	'Langenthal Gaswerk': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
	'Langenthal, Gaswerkstrasse': ['Langenthal Gaswerk', 'Langenthal, Gaswerkstrasse'],
	'Saint-Louis (Haut-Rhin)': ['Saint-Louis (Haut-Rhin)', 'St-Louis, Gare de Saint-Louis'],
	'St-Louis, Gare de Saint-Louis': ['Saint-Louis (Haut-Rhin)', 'St-Louis, Gare de Saint-Louis'],
	'Basel St. Johann': ['Basel St. Johann', 'Basel, Bahnhof St. Johann'],
	'Basel, Bahnhof St. Johann': ['Basel St. Johann', 'Basel, Bahnhof St. Johann'],
	'Olten, Leberngasse': ['Olten, Leberngasse', 'Olten, Schützenmatte'],
	'Olten, Schützenmatte': ['Olten, Leberngasse', 'Olten, Schützenmatte'],
	'Balsthal, Thalbrücke': ['Balsthal, Thalbrücke'],
	'Thalbrücke': ['Balsthal, Thalbrücke', 'Thalbrücke'],
	'Vignogn': ['Vignogn, vitg', 'Vignogn, Baselgia'],
	'Bern, Postautostation ': ['Bern, Hauptbahnhof'],
	'Sursee': ['Sursee', 'Sursee, Schnydermatt', 'Sursee, Bahnhof'],
	'Fribourg/Freiburg': ['Fribourg/Freiburg', 'Fribourg/Freiburg, gare rout.', 'Fribourg/Freiburg, Pl. gare', 'Fribourg/Freiburg, Richemond/gare', 'Fribourg/Freiburg, gare/Tivoli', 'Fribourg/Freiburg, gare/Colisée'],
	'Fribourg/Freiburg, gare rout.': ['Fribourg/Freiburg', 'Fribourg/Freiburg, Pl. gare'],
	'Fribourg/Freiburg, Pl. gare': ['Fribourg/Freiburg', 'Fribourg/Freiburg, gare rout.'],
	'Lauterbrunnen (Seilbahn)': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Lauterbrunnen, Bahnhof': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Lauterbrunnen': ['Lauterbrunnen', 'Lauterbrunnen, Bahnhof' , 'Lauterbrunnen (Seilbahn)'],
	'Col-du-Pillon (téléphérique)': ['Col-du-Pillon (téléphérique)', 'Col-du-Pillon, Glacier 3000'],
	'Col-du-Pillon, Glacier 3000': ['Col-du-Pillon (téléphérique)', 'Col-du-Pillon, Glacier 3000'],
	'Biel/Bienne Magglingenb.(Funi)': ['Biel/Bienne Magglingenb.(Funi)', 'Biel/Bienne, Magglingenbahn'],
	'Biel/Bienne, Magglingenbahn': ['Biel/Bienne Magglingenb.(Funi)', 'Biel/Bienne, Magglingenbahn'],
	'Biel/Bienne Leubringenb.(Funi)': ['Biel/Bienne Leubringenb.(Funi)', 'Biel/Bienne, Leubringenbahn'],
	'Biel/Bienne, Leubringenbahn': ['Biel/Bienne Leubringenb.(Funi)', 'Biel/Bienne, Leubringenbahn'],
	'Evilard, place du village': ['Evilard/Leubringen', 'Evilard, place du village'],
	'Evilard/Leubringen': ['Evilard/Leubringen', 'Evilard, place du village'],
	'Magglingen, Seilbahn': ['Magglingen/Macolin', 'Magglingen, Seilbahn'],
	'Magglingen/Macolin': ['Magglingen/Macolin', 'Magglingen, Seilbahn'],
	'Brig': ['Brig', 'Brig Bahnhofplatz', 'Brig, Bahnhof', 'Brig, Bahnhofplatz'],
	'Brig Bahnhofplatz': ['Brig', 'Brig Bahnhofplatz', 'Brig, Bahnhof', 'Brig, Bahnhofplatz'],
	
	'Samnaun-Ravaisch, Bergbahnen': ['Samnaun-Ravaisch, Bergbahnen', 'Samnaun-Ravaisch (Bergbahn)'],
	'Samnaun-Ravaisch (Bergbahn)': ['Samnaun-Ravaisch, Bergbahnen', 'Samnaun-Ravaisch (Bergbahn)'],
	'Scuol, Clozza': ['Scuol, Clozza', 'Scuol, Pütvia'],
	'Scuol, Pütvia': ['Scuol, Clozza', 'Scuol, Pütvia'],
	'Ftan Baraigla': ['Ftan Baraigla', 'Ftan, Baraigla'],
	'Ftan, Baraigla': ['Ftan Baraigla', 'Ftan, Baraigla'],
	'Ardez': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Ardez, staziun': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Ardez, Bröl': ['Ardez', 'Ardez, staziun', 'Ardez, Bröl'],
	'Lavin': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Lavin, staziun': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Lavin, Plazza Gronda': ['Lavin', 'Lavin, staziun', 'Lavin, Plazza Gronda'],
	'Susch': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'Susch, staziun': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'Susch, Plaz': ['Susch', 'Susch, staziun', 'Susch, Plaz'],
	'S-chanf Marathon': ['S-chanf Marathon', 'S-chanf, Zielgelände ESM'],
	'S-chanf, Zielgelände ESM': ['S-chanf Marathon', 'S-chanf, Zielgelände ESM'],
	'S-chanf': ['S-chanf', 'S-chanf, staziun', 'S-chanf, Chesa Cumünela'],
	'S-chanf, Chesa Cumünela': ['S-chanf', 'S-chanf, staziun', 'S-chanf, Chesa Cumünela'],
	'Madulain': ['Madulain', 'Madulain, vih'],
	'Madulain, vih': ['Madulain', 'Madulain, vih'],
	'La Punt Chamues-ch': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch, Abzw Albula', 'La Punt, Krone'],
	'La Punt Chamues-ch, Bahnhof': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch, Abzw Albula', 'La Punt, Krone'],
	'La Punt Chamues-ch, Abzw Albula': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch, Abzw Albula', 'La Punt, Krone'],
	'La Punt, Krone': ['La Punt Chamues-ch', 'La Punt Chamues-ch, Bahnhof', 'La Punt Chamues-ch, Abzw Albula', 'La Punt, Krone'],
	'Samedan': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Samedan, Bahnhof': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Samedan, Plazzet': ['Samedan', 'Samedan, Bahnhof', 'Samedan, Plazzet'],
	'Celerina': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Schlarigna': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Cresta Palace': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Punt Schlattain': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'Celerina, Centrum': ['Celerina', 'Celerina, Cresta Palace', 'Celerina, Punt Schlattain', 'Celerina, Centrum'],
	'St. Moritz, Schulhausplatz': ['St. Moritz, Schulhausplatz', 'St. Moritz (Standseilbahn)'],
	'St. Moritz (Standseilbahn)': ['St. Moritz, Schulhausplatz', 'St. Moritz (Standseilbahn)'],
	'St. Moritz Bad, Signalbahn': ['St. Moritz Bad, Signalbahn', 'St. Moritz Bad (Signalbahn)'],
	'St. Moritz Bad (Signalbahn)': ['St. Moritz Bad, Signalbahn', 'St. Moritz Bad (Signalbahn)'],
	'Surlej, Corvatschbahn': ['Surlej, Corvatschbahn', 'Silvaplana Surlej (Corvatsch)'],
	'Silvaplana Surlej (Corvatsch)': ['Surlej, Corvatschbahn', 'Silvaplana Surlej (Corvatsch)'],
	'Sils/Segl Maria, Furtschellasb.': ['Sils/Segl Maria, Furtschellasb.', 'Sils Maria (Furtschellasbahn)'],
	'Sils Maria (Furtschellasbahn)': ['Sils/Segl Maria, Furtschellasb.', 'Sils Maria (Furtschellasbahn)'],
	'Sils/Segl Maria, Posta': ['Sils/Segl Maria, Posta', 'Sils/Segl Maria Barchiröls'],
	'Sils/Segl Maria Barchiröls': ['Sils/Segl Maria, Posta', 'Sils/Segl Maria Barchiröls'],
	'Sils/Segl Baselgia, San Lurench': ['Sils/Segl Baselgia, San Lurench', 'Chastè'],
	'Chastè': ['Sils/Segl Baselgia, San Lurench', 'Chastè'],
	'Maloja, Capolago': ['Maloja, Capolago', 'Maloja (See)'],
	'Maloja (See)': ['Maloja, Capolago', 'Maloja (See)'],
	'Celerina Staz': ['Celerina Staz', 'Celerina, Buogl'],
	'Schlarigna Staz': ['Celerina Staz', 'Celerina, Buogl'],
	'Celerina, Buogl': ['Celerina Staz', 'Celerina, Buogl'],
	'Punt Muragl': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl Staz': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl, Talstation': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Punt Muragl (Talstation)': ['Punt Muragl', 'Punt Muragl Staz', 'Punt Muragl, Talstation', 'Punt Muragl (Talstation)'],
	'Surovas': ['Pontresina, Post', 'Surovas'],
	'Pontresina, Post': ['Pontresina, Post', 'Surovas'],
	'Morteratsch': ['Morteratsch', 'Morteratsch, Abzweigung'],
	'Morteratsch, Abzweigung': ['Morteratsch', 'Morteratsch, Abzweigung'],
	'Bernina Diavolezza': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Diavolezza Talstation'],
	'Bernina Diavolezza, Bahnhof': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Diavolezza Talstation'],
	'Diavolezza Talstation': ['Bernina Diavolezza', 'Bernina Diavolezza, Bahnhof', 'Diavolezza Talstation'],
	'Bernina Lagalb': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Bernina, Lagalbbahn': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Curtinatsch': ['Bernina Lagalb', 'Bernina, Lagalbbahn', 'Curtinatsch'],
	'Ospizio Bernina': ['Ospizio Bernina', 'Ospizio Bernina, Albergo'],
	'Ospizio Bernina, Albergo': ['Ospizio Bernina', 'Ospizio Bernina, Albergo'],
	'Meschino': ['Miralago', 'Miralago, Stazione'],
	'Brusio': ['Brusio', 'Brusio, Posta'],
	'Brusio, Posta': ['Brusio', 'Brusio, Posta'],
	'Campascio': ['Campascio', 'Campascio, Strada'],
	'Campascio, Strada': ['Campascio', 'Campascio, Strada'],
	'Tirano': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
	'Tirano, Stazione': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
	'Tirano FS': ['Tirano', 'Tirano, Stazione', 'Tirano FS'],
};